version: 2

defaults: &defaults
  working_directory: ~/hela-core
  docker:
    - image: circleci/node:8

restore_modules_cache: &restore_modules_cache
  restore_cache:
    keys:
    - hela-core-{{ checksum "yarn.lock" }}
    # fallback to using the latest cache if no exact match is found
    - hela-core-


jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Installing dependencies
          command: yarn install
      - save_cache:
          key: hela-core-{{ checksum "yarn.lock" }}
          paths: node_modules
      - run:
          name: Remove node_modules to cleanup workspace
          command: rm -rf node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Running tests and checks
          command: yarn test
      - run:
          name: Sending test coverage to CodeCov
          command: bash <(curl -s https://codecov.io/bash)

  release:
    <<: *defaults
    steps:
      - checkout
      - *restore_modules_cache
      - run:
          name: Releasing and publishing
          command: yarn run release

workflows:
  version: 2
  automated:
    jobs:
      - install
      - test:
          requires:
            - install
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
          context: org-global
